<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \\Http\Requests\EventStoreRequest
 */
class EventStoreRequestTest extends TestCase
{
/** @var \\Http\Requests\EventStoreRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \\Http\Requests\EventStoreRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

$actual = $this->subject->authorize();

$this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

$actual = $this->subject->rules();

$this->assertValidationRules([
            'eventName' => 'required|max:255',
            'eventTypeID' => 'required',
            'slug' => 'required|unique:org-events,slug',
        ], $actual);
    }

    // test cases...
}
